version: "3.8"
services:
  app:
    container_name: app_host
    build: ./infra/php
    volumes:
      - ./backend:/work

  web:
    container_name: web_host
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    container_name: mysql_host
    build: ./infra/mysql
    ports:
      - 3306:3306
