version: "3.8"
services:
  app:
    container_name: app_host
    build: ./infra/php
    volumes:
      - ./backend:/work

  db:
    container_name: mysql_host
    build: ./infra/mysql
    ports:
      - 3306:3306
