version: "3.8"
services:
  app:
    hostname: app
    container_name: sample
    build: ./infra/php
    volumes:
      - ./backend:/work

  web:
    hostname: web
    container_name: sample_web
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    hostname: db
    container_name: sample_db
    build: ./infra/mysql
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
